name: Publish to VSCode Marketplace
on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Publish Extension
        run: pnpx vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
