name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Release
        run: pnpx standard-version
      - name: Push to repo
        run: git push --follow-tags origin mainline
