name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npx standard-version
      - name: 'Push to repo'
        run: git push --follow-tags origin mainline